name: Store API Key

on:
  push:
    branches: [ main ]

jobs:
  store-api-key:
    name: Store API Key
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Store API Key
        uses: tangtracy/git-auto-commit-action@v4
        with:
          commit_message: "Store API key"
          file_pattern: "../gpt/gpt.js"
          branch: "main"
          file_content: |
            const API_KEY = '${{ secrets.MY_OPENAI_KEY }}';
